### ISSUE TITLE
Implementer "filtre"

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#23]
Implementer filter funktionaliteten

**Comment by Pilen** [comment]
Virker de som forventet?

**Comment by Piltoft** [comment]
Den loader ikke lege

**Comment by Piltoft** [comment]
legedatabasen.js:84 Uncaught TypeError: Cannot read property 'name' of undefined
    at http://legedatabasen.dk/legedatabasen.js:84:69
    at Array.map (native)
    at Object.success (http://legedatabasen.dk/legedatabasen.js:72:21)
    at i (http://legedatabasen.dk/bower_components/jquery/dist/jquery.min.js:2:27983)
    at Object.fireWith [as resolveWith](http://legedatabasen.dk/bower_components/jquery/dist/jquery.min.js:2:28749)
    at A (http://legedatabasen.dk/bower_components/jquery/dist/jquery.min.js:4:14203)
    at XMLHttpRequest.<anonymous> (http://legedatabasen.dk/bower_components/jquery/dist/jquery.min.js:4:16491)
legedatabasen.js:429 Uncaught TypeError: Cannot read property 'clear' of undefined
    at resetDisplay (http://legedatabasen.dk/legedatabasen.js:429:11)
    at showSubmenu (http://legedatabasen.dk/legedatabasen.js:409:5)
    at HTMLImageElement.<anonymous> (http://legedatabasen.dk/legedatabasen.js:187:9)
    at HTMLImageElement.dispatch (http://legedatabasen.dk/bower_components/jquery/dist/jquery.min.js:3:10315)
    at HTMLImageElement.q.handle (http://legedatabasen.dk/bower_components/jquery/dist/jquery.min.js:3:8342)

**Comment by Pilen** [comment]
Fejlen er at legen har mistet sit billede, så prøver den sin kategori, men den har heller ingen kategori

I har rettet i "-- Live Test --"

**Comment by Piltoft** [comment]
Jeg har skiftet billedet ud, på Peters ønske

**Comment by Piltoft** [comment]
Jeg har tildelt den alle kategorier

**Comment by Pilen** [comment]
Nu burde den også få et default.png billede hvis intet er valgt.
